package flipr

// stamp.go -- Generated by clients/bin/stamp.sh at release; committed as
// dev/unknown between tags so a checkout announces itself as one
// (CONTRACT.md section 8). Do not edit; clients/bin/stamp.sh go --write
// regenerates it. A build's -ldflags -X on these two names still wins.

// ClientTag and ClientHash identify this client on the wire as
// X-Flipr-Client: go/<tag>/<hash>: the tag this source was released at and
// the first twelve hex digits of the sha256 over flipr.go and retry.go there.
var (
	ClientTag  = "v1.1.1"
	ClientHash = "99515a449bf1"
)
