// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: flipr/v1/flipr.proto

// flipr -- the flag store the whole mesh reads before it does anything
// expensive.
//
// Named for the original at Uber: a boolean store, and you FLIP the value.
// That is the whole idea and the schema is deliberately built to stay that
// small. No experiments, no percentage rollouts, no targeting, no audience
// segmentation. Those are what made the product complicated and none of them
// are wanted here.
//
// The one requirement that shapes everything below: IF FLIPR IS DOWN, THE
// NETWORK IS DOWN. Clients cache the last value they read so a live flipr does
// not answer the same question hundreds of times a second -- but the cache is
// a PERFORMANCE optimisation, never a fallback. A client still checks flipr is
// there, and if it is not, the client fails rather than quietly serving a
// stale flag. Clients cache the last read, and always check that flipr is
// there.

package fliprv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A flag's value. A oneof rather than a bare bool because the charter names a
// non-boolean case outright -- "nightly data smoothing" set to `surreal` or
// `claude` -- and encoding that as two booleans would let both be true.
//
// Three cases and no more. Anything that wants richer structure is a design
// smell at this layer: flipr answers "what should I do", not "what is my
// configuration".
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_BoolValue
	//	*Value_StringValue
	//	*Value_IntValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_IntValue) isValue_Kind() {}

// One flag, and everything known about it.
type Flag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dotted, and the dots are the hierarchy: `nightly.smoothing`. The front end
	// renders the tree by splitting on the dot rather than the schema carrying a
	// nested type, which keeps the store flat and the wire trivial.
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Why this flag exists, in one line, for whoever meets it at 03:20.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Does turning this on cost network, disk, cpu, or a model call?
	//
	// THE EMERGENCY PAGE IS THE SET WHERE THIS IS TRUE. It is a projection of
	// this field, never a hand-maintained second list, so the two pages cannot
	// drift apart.
	Expensive bool `protobuf:"varint,4,opt,name=expensive,proto3" json:"expensive,omitempty"`
	// Set by flipr, not by the caller: when this value was last written.
	UpdatedAt     string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{1}
}

func (x *Flag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Flag) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Flag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flag) GetExpensive() bool {
	if x != nil {
		return x.Expensive
	}
	return false
}

func (x *Flag) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// A namespace is one service at one version.
//
// The charter is explicit: keyed to the service AND its version, which is its
// commit hash at deploy. `albatross-xyz` and `albatross-abc` are different
// namespaces and both live under `albatross`. That is what makes a deploy
// able to publish its own flags without trampling the version still running.
type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // "albatross"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // the commit hash at deploy
	Flags         []*Flag                `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{2}
}

func (x *Namespace) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Namespace) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Namespace) GetFlags() []*Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

type GetFlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagRequest) Reset() {
	*x = GetFlagRequest{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagRequest) ProtoMessage() {}

func (x *GetFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagRequest.ProtoReflect.Descriptor instead.
func (*GetFlagRequest) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{3}
}

func (x *GetFlagRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetFlagRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetFlagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Flag  *Flag                  `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	// The store revision this answer was read at (see GetNamespaceRequest).
	Revision      uint64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagResponse) Reset() {
	*x = GetFlagResponse{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagResponse) ProtoMessage() {}

func (x *GetFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagResponse.ProtoReflect.Descriptor instead.
func (*GetFlagResponse) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{4}
}

func (x *GetFlagResponse) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *GetFlagResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// The call a client makes on startup and then rarely: fetch the whole
// namespace in one round trip and cache it.
type GetNamespaceRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Service string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// THE CHECKPOINT. Every write bumps the store's
	// revision by one, inside the write's own transaction. A reader that
	// holds the revision it last saw sends it here; when it equals the
	// current one flipr answers `unchanged` with the revision and no flags,
	// one integer compared with one integer before anything is read. That is
	// the whole cost of a consumer polling on its interval. Zero means "give
	// me everything", which is what a client sends first.
	Since         uint64 `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceRequest) Reset() {
	*x = GetNamespaceRequest{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceRequest) ProtoMessage() {}

func (x *GetNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceRequest.ProtoReflect.Descriptor instead.
func (*GetNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{5}
}

func (x *GetNamespaceRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetNamespaceRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetNamespaceRequest) GetSince() uint64 {
	if x != nil {
		return x.Since
	}
	return 0
}

type GetNamespaceResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The store revision this answer was read at.
	Revision uint64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	// True when `since` equals the current revision: nothing has changed
	// anywhere in the store since the caller last looked, and `namespace` is
	// unset. The caller keeps what it has.
	Unchanged     bool `protobuf:"varint,3,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceResponse) Reset() {
	*x = GetNamespaceResponse{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceResponse) ProtoMessage() {}

func (x *GetNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceResponse.ProtoReflect.Descriptor instead.
func (*GetNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{6}
}

func (x *GetNamespaceResponse) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *GetNamespaceResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *GetNamespaceResponse) GetUnchanged() bool {
	if x != nil {
		return x.Unchanged
	}
	return false
}

// The flip.
type SetFlagRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Service string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Key     string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value   *Value                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// Who or what is flipping this, and why. Recorded and shipped to kafka.
	// Not optional in practice: a flag flipped for no stated reason is how an
	// outage becomes unexplainable, and this effort has already lost one event
	// to exactly that.
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFlagRequest) Reset() {
	*x = SetFlagRequest{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFlagRequest) ProtoMessage() {}

func (x *SetFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFlagRequest.ProtoReflect.Descriptor instead.
func (*SetFlagRequest) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{7}
}

func (x *SetFlagRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SetFlagRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SetFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetFlagRequest) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetFlagRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SetFlagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Flag  *Flag                  `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	// The revision this flip created: the number a restore names.
	Revision      uint64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFlagResponse) Reset() {
	*x = SetFlagResponse{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFlagResponse) ProtoMessage() {}

func (x *SetFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFlagResponse.ProtoReflect.Descriptor instead.
func (*SetFlagResponse) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{8}
}

func (x *SetFlagResponse) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *SetFlagResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// Build-time onboarding. Part of every deployed application's BUILD PROCESS is
// publishing its current flipr settings, so a service arrives already
// described rather than being registered by hand afterwards.
//
// Idempotent: publishing the same namespace twice is the normal case, because
// a redeploy of the same commit republishes.
type PublishNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishNamespaceRequest) Reset() {
	*x = PublishNamespaceRequest{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishNamespaceRequest) ProtoMessage() {}

func (x *PublishNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishNamespaceRequest.ProtoReflect.Descriptor instead.
func (*PublishNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{9}
}

func (x *PublishNamespaceRequest) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

type PublishNamespaceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FlagsPublished int32                  `protobuf:"varint,1,opt,name=flags_published,json=flagsPublished,proto3" json:"flags_published,omitempty"`
	// The revision after this publish. A publish is a write and moves it,
	// even one that changed no value; a service republishing on every loop
	// shows as a revision that moves while nobody is flipping.
	Revision      uint64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishNamespaceResponse) Reset() {
	*x = PublishNamespaceResponse{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishNamespaceResponse) ProtoMessage() {}

func (x *PublishNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishNamespaceResponse.ProtoReflect.Descriptor instead.
func (*PublishNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{10}
}

func (x *PublishNamespaceResponse) GetFlagsPublished() int32 {
	if x != nil {
		return x.FlagsPublished
	}
	return 0
}

func (x *PublishNamespaceResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// The home page: every service that has flags, and every version of it.
type ListNamespacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{11}
}

type ListNamespacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []*Namespace           `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{12}
}

func (x *ListNamespacesResponse) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ListNamespacesResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// Namespace retirement: the garbage collection the version-keyed scheme
// needs. Every deploy mints service@commit and nothing retired them, so the
// store accumulated 21 dead dodo namespaces in one evening of deploys. A
// delete is an OPERATION: it carries a reason, lands in the immutable log,
// and REPLAYS after a store wipe -- without that, every deleted namespace
// would resurrect from kafka at the next wipe-recovery.
type DeleteNamespaceRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Service string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Required, same rule as SetFlag: an unexplained delete is how an outage
	// becomes unexplainable.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceRequest) Reset() {
	*x = DeleteNamespaceRequest{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceRequest) ProtoMessage() {}

func (x *DeleteNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteNamespaceRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DeleteNamespaceRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeleteNamespaceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlagsRemoved  int32                  `protobuf:"varint,1,opt,name=flags_removed,json=flagsRemoved,proto3" json:"flags_removed,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceResponse) Reset() {
	*x = DeleteNamespaceResponse{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceResponse) ProtoMessage() {}

func (x *DeleteNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteNamespaceResponse) GetFlagsRemoved() int32 {
	if x != nil {
		return x.FlagsRemoved
	}
	return 0
}

func (x *DeleteNamespaceResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// The liveness check every client makes before trusting its cache. Kept
// deliberately trivial -- no store read, no allocation worth naming -- because
// every service in the mesh calls it and it must never be the reason flipr is
// slow.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{15}
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// flipr's own version, so a client can notice it is talking to something
	// it does not expect.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Minted once when the store file is CREATED and persisted inside it, so a
	// flipr that lost its store comes back wearing a different generation. This
	// is the wipe report: it rides the liveness check every client already makes
	// on every read, so nobody has to poll a separate endpoint to learn the
	// store was nuked. A client that sees the generation change re-publishes its
	// declared defaults before serving -- the self-heal is collaborative.
	StoreGeneration string `protobuf:"bytes,2,opt,name=store_generation,json=storeGeneration,proto3" json:"store_generation,omitempty"`
	// The store revision now: rides the ping every client makes, so a client
	// learns "something changed since I last looked" for the price of the
	// liveness check it was making anyway, and refreshes only then. A client
	// compares for inequality, never for "greater than": a store healed from
	// an emptier file than the one it wrote can answer a lower number, and
	// any change is a reason to look again.
	Revision      uint64 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_flipr_v1_flipr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flipr_v1_flipr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_flipr_v1_flipr_proto_rawDescGZIP(), []int{16}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetStoreGeneration() string {
	if x != nil {
		return x.StoreGeneration
	}
	return ""
}

func (x *PingResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_flipr_v1_flipr_proto protoreflect.FileDescriptor

const file_flipr_v1_flipr_proto_rawDesc = "" +
	"\n" +
	"\x14flipr/v1/flipr.proto\x12\bflipr.v1\"t\n" +
	"\x05Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValueB\x06\n" +
	"\x04kind\"\x9e\x01\n" +
	"\x04Flag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.flipr.v1.ValueR\x05value\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\texpensive\x18\x04 \x01(\bR\texpensive\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"e\n" +
	"\tNamespace\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12$\n" +
	"\x05flags\x18\x03 \x03(\v2\x0e.flipr.v1.FlagR\x05flags\"V\n" +
	"\x0eGetFlagRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"Q\n" +
	"\x0fGetFlagResponse\x12\"\n" +
	"\x04flag\x18\x01 \x01(\v2\x0e.flipr.v1.FlagR\x04flag\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"_\n" +
	"\x13GetNamespaceRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x04R\x05since\"\x83\x01\n" +
	"\x14GetNamespaceResponse\x121\n" +
	"\tnamespace\x18\x01 \x01(\v2\x13.flipr.v1.NamespaceR\tnamespace\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12\x1c\n" +
	"\tunchanged\x18\x03 \x01(\bR\tunchanged\"\x95\x01\n" +
	"\x0eSetFlagRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x04 \x01(\v2\x0f.flipr.v1.ValueR\x05value\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"Q\n" +
	"\x0fSetFlagResponse\x12\"\n" +
	"\x04flag\x18\x01 \x01(\v2\x0e.flipr.v1.FlagR\x04flag\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"L\n" +
	"\x17PublishNamespaceRequest\x121\n" +
	"\tnamespace\x18\x01 \x01(\v2\x13.flipr.v1.NamespaceR\tnamespace\"_\n" +
	"\x18PublishNamespaceResponse\x12'\n" +
	"\x0fflags_published\x18\x01 \x01(\x05R\x0eflagsPublished\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"\x17\n" +
	"\x15ListNamespacesRequest\"i\n" +
	"\x16ListNamespacesResponse\x123\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x13.flipr.v1.NamespaceR\n" +
	"namespaces\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"d\n" +
	"\x16DeleteNamespaceRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"Z\n" +
	"\x17DeleteNamespaceResponse\x12#\n" +
	"\rflags_removed\x18\x01 \x01(\x05R\fflagsRemoved\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"\r\n" +
	"\vPingRequest\"o\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12)\n" +
	"\x10store_generation\x18\x02 \x01(\tR\x0fstoreGeneration\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision2\x9c\x04\n" +
	"\fFliprService\x12>\n" +
	"\aGetFlag\x12\x18.flipr.v1.GetFlagRequest\x1a\x19.flipr.v1.GetFlagResponse\x12M\n" +
	"\fGetNamespace\x12\x1d.flipr.v1.GetNamespaceRequest\x1a\x1e.flipr.v1.GetNamespaceResponse\x12>\n" +
	"\aSetFlag\x12\x18.flipr.v1.SetFlagRequest\x1a\x19.flipr.v1.SetFlagResponse\x12Y\n" +
	"\x10PublishNamespace\x12!.flipr.v1.PublishNamespaceRequest\x1a\".flipr.v1.PublishNamespaceResponse\x12S\n" +
	"\x0eListNamespaces\x12\x1f.flipr.v1.ListNamespacesRequest\x1a .flipr.v1.ListNamespacesResponse\x12V\n" +
	"\x0fDeleteNamespace\x12 .flipr.v1.DeleteNamespaceRequest\x1a!.flipr.v1.DeleteNamespaceResponse\x125\n" +
	"\x04Ping\x12\x15.flipr.v1.PingRequest\x1a\x16.flipr.v1.PingResponseB\x96\x01\n" +
	"\fcom.flipr.v1B\n" +
	"FliprProtoP\x01Z9github.com/janearc/flipr-dist/clients/go/flipr/v1;fliprv1\xa2\x02\x03FXX\xaa\x02\bFlipr.V1\xca\x02\bFlipr\\V1\xe2\x02\x14Flipr\\V1\\GPBMetadata\xea\x02\tFlipr::V1b\x06proto3"

var (
	file_flipr_v1_flipr_proto_rawDescOnce sync.Once
	file_flipr_v1_flipr_proto_rawDescData []byte
)

func file_flipr_v1_flipr_proto_rawDescGZIP() []byte {
	file_flipr_v1_flipr_proto_rawDescOnce.Do(func() {
		file_flipr_v1_flipr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flipr_v1_flipr_proto_rawDesc), len(file_flipr_v1_flipr_proto_rawDesc)))
	})
	return file_flipr_v1_flipr_proto_rawDescData
}

var file_flipr_v1_flipr_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_flipr_v1_flipr_proto_goTypes = []any{
	(*Value)(nil),                    // 0: flipr.v1.Value
	(*Flag)(nil),                     // 1: flipr.v1.Flag
	(*Namespace)(nil),                // 2: flipr.v1.Namespace
	(*GetFlagRequest)(nil),           // 3: flipr.v1.GetFlagRequest
	(*GetFlagResponse)(nil),          // 4: flipr.v1.GetFlagResponse
	(*GetNamespaceRequest)(nil),      // 5: flipr.v1.GetNamespaceRequest
	(*GetNamespaceResponse)(nil),     // 6: flipr.v1.GetNamespaceResponse
	(*SetFlagRequest)(nil),           // 7: flipr.v1.SetFlagRequest
	(*SetFlagResponse)(nil),          // 8: flipr.v1.SetFlagResponse
	(*PublishNamespaceRequest)(nil),  // 9: flipr.v1.PublishNamespaceRequest
	(*PublishNamespaceResponse)(nil), // 10: flipr.v1.PublishNamespaceResponse
	(*ListNamespacesRequest)(nil),    // 11: flipr.v1.ListNamespacesRequest
	(*ListNamespacesResponse)(nil),   // 12: flipr.v1.ListNamespacesResponse
	(*DeleteNamespaceRequest)(nil),   // 13: flipr.v1.DeleteNamespaceRequest
	(*DeleteNamespaceResponse)(nil),  // 14: flipr.v1.DeleteNamespaceResponse
	(*PingRequest)(nil),              // 15: flipr.v1.PingRequest
	(*PingResponse)(nil),             // 16: flipr.v1.PingResponse
}
var file_flipr_v1_flipr_proto_depIdxs = []int32{
	0,  // 0: flipr.v1.Flag.value:type_name -> flipr.v1.Value
	1,  // 1: flipr.v1.Namespace.flags:type_name -> flipr.v1.Flag
	1,  // 2: flipr.v1.GetFlagResponse.flag:type_name -> flipr.v1.Flag
	2,  // 3: flipr.v1.GetNamespaceResponse.namespace:type_name -> flipr.v1.Namespace
	0,  // 4: flipr.v1.SetFlagRequest.value:type_name -> flipr.v1.Value
	1,  // 5: flipr.v1.SetFlagResponse.flag:type_name -> flipr.v1.Flag
	2,  // 6: flipr.v1.PublishNamespaceRequest.namespace:type_name -> flipr.v1.Namespace
	2,  // 7: flipr.v1.ListNamespacesResponse.namespaces:type_name -> flipr.v1.Namespace
	3,  // 8: flipr.v1.FliprService.GetFlag:input_type -> flipr.v1.GetFlagRequest
	5,  // 9: flipr.v1.FliprService.GetNamespace:input_type -> flipr.v1.GetNamespaceRequest
	7,  // 10: flipr.v1.FliprService.SetFlag:input_type -> flipr.v1.SetFlagRequest
	9,  // 11: flipr.v1.FliprService.PublishNamespace:input_type -> flipr.v1.PublishNamespaceRequest
	11, // 12: flipr.v1.FliprService.ListNamespaces:input_type -> flipr.v1.ListNamespacesRequest
	13, // 13: flipr.v1.FliprService.DeleteNamespace:input_type -> flipr.v1.DeleteNamespaceRequest
	15, // 14: flipr.v1.FliprService.Ping:input_type -> flipr.v1.PingRequest
	4,  // 15: flipr.v1.FliprService.GetFlag:output_type -> flipr.v1.GetFlagResponse
	6,  // 16: flipr.v1.FliprService.GetNamespace:output_type -> flipr.v1.GetNamespaceResponse
	8,  // 17: flipr.v1.FliprService.SetFlag:output_type -> flipr.v1.SetFlagResponse
	10, // 18: flipr.v1.FliprService.PublishNamespace:output_type -> flipr.v1.PublishNamespaceResponse
	12, // 19: flipr.v1.FliprService.ListNamespaces:output_type -> flipr.v1.ListNamespacesResponse
	14, // 20: flipr.v1.FliprService.DeleteNamespace:output_type -> flipr.v1.DeleteNamespaceResponse
	16, // 21: flipr.v1.FliprService.Ping:output_type -> flipr.v1.PingResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_flipr_v1_flipr_proto_init() }
func file_flipr_v1_flipr_proto_init() {
	if File_flipr_v1_flipr_proto != nil {
		return
	}
	file_flipr_v1_flipr_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_BoolValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_IntValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flipr_v1_flipr_proto_rawDesc), len(file_flipr_v1_flipr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flipr_v1_flipr_proto_goTypes,
		DependencyIndexes: file_flipr_v1_flipr_proto_depIdxs,
		MessageInfos:      file_flipr_v1_flipr_proto_msgTypes,
	}.Build()
	File_flipr_v1_flipr_proto = out.File
	file_flipr_v1_flipr_proto_goTypes = nil
	file_flipr_v1_flipr_proto_depIdxs = nil
}
