// stamp.ts -- GENERATED by clients/bin/stamp.sh at package build; committed
// as dev/unknown so a checkout announces itself as one (CONTRACT.md
// section 8). Do not edit; clients/bin/stamp.sh typescript --write regenerates it.
export const STAMP = { tag: "v1.1.0", hash: "0200acc67c5c" } as const;
