# _stamp.py -- GENERATED by clients/bin/stamp.sh at package build; committed
# as dev/unknown so a checkout announces itself as one (CONTRACT.md
# section 8). Do not edit; clients/bin/stamp.sh python --write regenerates it.
CLIENT_TAG = "v1.1.0"
CLIENT_HASH = "130ff74ee4e9"
